<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CartItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cart_items')->delete();
        
        \DB::table('cart_items')->insert(array (
            0 => 
            array (
                'additional' => '{"_token": "gbtIu2pobdLIbusFG9hwyAjzltXs7zw5wit4ZYPM", "quantity": 1, "product_id": "1"}',
                'applied_cart_rule_ids' => '',
                'base_discount_amount' => '0.0000',
                'base_price' => '10.0000',
                'base_tax_amount' => '0.0000',
                'base_total' => '10.0000',
                'base_total_weight' => '20.0000',
                'cart_id' => 1,
                'coupon_code' => NULL,
                'created_at' => '2021-03-23 11:25:02',
                'custom_price' => NULL,
                'discount_amount' => '0.0000',
                'discount_percent' => '0.0000',
                'id' => 1,
                'name' => 'product1',
                'parent_id' => NULL,
                'price' => '10.0000',
                'product_id' => 1,
                'quantity' => 1,
                'sku' => '1',
                'tax_amount' => '0.0000',
                'tax_category_id' => NULL,
                'tax_percent' => '0.0000',
                'total' => '10.0000',
                'total_weight' => '20.0000',
                'type' => 'simple',
                'updated_at' => '2021-03-23 11:27:07',
                'weight' => '20.0000',
            ),
            1 => 
            array (
                'additional' => '{"_token": "r2k5EVBdGcSjFSH4omzyYI28Ew0DoFD5BcUcj5ih", "quantity": 1, "product_id": "1"}',
                'applied_cart_rule_ids' => '',
                'base_discount_amount' => '0.0000',
                'base_price' => '10.0000',
                'base_tax_amount' => '0.0000',
                'base_total' => '10.0000',
                'base_total_weight' => '20.0000',
                'cart_id' => 2,
                'coupon_code' => NULL,
                'created_at' => '2021-03-23 12:02:31',
                'custom_price' => NULL,
                'discount_amount' => '0.0000',
                'discount_percent' => '0.0000',
                'id' => 2,
                'name' => 'product1',
                'parent_id' => NULL,
                'price' => '10.0000',
                'product_id' => 1,
                'quantity' => 1,
                'sku' => '1',
                'tax_amount' => '0.0000',
                'tax_category_id' => NULL,
                'tax_percent' => '0.0000',
                'total' => '10.0000',
                'total_weight' => '20.0000',
                'type' => 'simple',
                'updated_at' => '2021-03-23 12:02:31',
                'weight' => '20.0000',
            ),
            2 => 
            array (
                'additional' => '{"_token": "mEhiIPt6445z5h5zGFhRJKjzBgfKEDdVAftUCvPm", "quantity": 1, "product_id": "1"}',
                'applied_cart_rule_ids' => '',
                'base_discount_amount' => '0.0000',
                'base_price' => '10.0000',
                'base_tax_amount' => '0.0000',
                'base_total' => '10.0000',
                'base_total_weight' => '20.0000',
                'cart_id' => 3,
                'coupon_code' => NULL,
                'created_at' => '2021-03-23 12:28:38',
                'custom_price' => NULL,
                'discount_amount' => '0.0000',
                'discount_percent' => '0.0000',
                'id' => 3,
                'name' => 'product1',
                'parent_id' => NULL,
                'price' => '10.0000',
                'product_id' => 1,
                'quantity' => 1,
                'sku' => '1',
                'tax_amount' => '0.0000',
                'tax_category_id' => NULL,
                'tax_percent' => '0.0000',
                'total' => '10.0000',
                'total_weight' => '20.0000',
                'type' => 'simple',
                'updated_at' => '2021-03-23 12:28:38',
                'weight' => '20.0000',
            ),
            3 => 
            array (
                'additional' => '{"_token": "TMSpzq9fNTLXiKvonWcOcAPFEPbTWgOm6NMivV50", "quantity": 1, "product_id": "1"}',
                'applied_cart_rule_ids' => '',
                'base_discount_amount' => '0.0000',
                'base_price' => '10.0000',
                'base_tax_amount' => '0.0000',
                'base_total' => '10.0000',
                'base_total_weight' => '20.0000',
                'cart_id' => 4,
                'coupon_code' => NULL,
                'created_at' => '2021-03-23 14:02:25',
                'custom_price' => NULL,
                'discount_amount' => '0.0000',
                'discount_percent' => '0.0000',
                'id' => 4,
                'name' => 'product1',
                'parent_id' => NULL,
                'price' => '10.0000',
                'product_id' => 1,
                'quantity' => 1,
                'sku' => '1',
                'tax_amount' => '0.0000',
                'tax_category_id' => NULL,
                'tax_percent' => '0.0000',
                'total' => '10.0000',
                'total_weight' => '20.0000',
                'type' => 'simple',
                'updated_at' => '2021-03-23 14:02:39',
                'weight' => '20.0000',
            ),
            4 => 
            array (
                'additional' => '{"_token": "zgQaP5Mm14sHLZQVDTeB6zY8EUw1SFCmXL256nAg", "quantity": 1, "product_id": "1"}',
                'applied_cart_rule_ids' => '',
                'base_discount_amount' => '0.0000',
                'base_price' => '10.0000',
                'base_tax_amount' => '0.0000',
                'base_total' => '10.0000',
                'base_total_weight' => '20.0000',
                'cart_id' => 5,
                'coupon_code' => NULL,
                'created_at' => '2021-03-23 15:13:28',
                'custom_price' => NULL,
                'discount_amount' => '0.0000',
                'discount_percent' => '0.0000',
                'id' => 5,
                'name' => 'product1',
                'parent_id' => NULL,
                'price' => '10.0000',
                'product_id' => 1,
                'quantity' => 1,
                'sku' => '1',
                'tax_amount' => '0.0000',
                'tax_category_id' => NULL,
                'tax_percent' => '0.0000',
                'total' => '10.0000',
                'total_weight' => '20.0000',
                'type' => 'simple',
                'updated_at' => '2021-03-23 15:13:33',
                'weight' => '20.0000',
            ),
            5 => 
            array (
                'additional' => '{"_token": "41Fd5Ibir8Js5eXyvaMP64PZ9O3odcUGTKasECyz", "quantity": 1, "product_id": "1"}',
                'applied_cart_rule_ids' => '',
                'base_discount_amount' => '0.0000',
                'base_price' => '10.0000',
                'base_tax_amount' => '0.0000',
                'base_total' => '10.0000',
                'base_total_weight' => '20.0000',
                'cart_id' => 6,
                'coupon_code' => NULL,
                'created_at' => '2021-03-23 20:30:20',
                'custom_price' => NULL,
                'discount_amount' => '0.0000',
                'discount_percent' => '0.0000',
                'id' => 6,
                'name' => 'product1',
                'parent_id' => NULL,
                'price' => '10.0000',
                'product_id' => 1,
                'quantity' => 1,
                'sku' => '1',
                'tax_amount' => '0.0000',
                'tax_category_id' => NULL,
                'tax_percent' => '0.0000',
                'total' => '10.0000',
                'total_weight' => '20.0000',
                'type' => 'simple',
                'updated_at' => '2021-03-23 21:09:09',
                'weight' => '20.0000',
            ),
            6 => 
            array (
                'additional' => '{"_token": "bEj1PdChQDQG89xRgPa8vD7jDf3DNytL86pQd9tX", "quantity": 3, "product_id": "1"}',
                'applied_cart_rule_ids' => '',
                'base_discount_amount' => '0.0000',
                'base_price' => '10.0000',
                'base_tax_amount' => '0.0000',
                'base_total' => '30.0000',
                'base_total_weight' => '60.0000',
                'cart_id' => 7,
                'coupon_code' => NULL,
                'created_at' => '2021-03-25 15:01:41',
                'custom_price' => NULL,
                'discount_amount' => '0.0000',
                'discount_percent' => '0.0000',
                'id' => 7,
                'name' => 'product1',
                'parent_id' => NULL,
                'price' => '10.0000',
                'product_id' => 1,
                'quantity' => 3,
                'sku' => '1',
                'tax_amount' => '0.0000',
                'tax_category_id' => NULL,
                'tax_percent' => '0.0000',
                'total' => '30.0000',
                'total_weight' => '60.0000',
                'type' => 'simple',
                'updated_at' => '2021-04-03 15:13:59',
                'weight' => '20.0000',
            ),
            7 => 
            array (
                'additional' => '{"_token": "RGg8GkYNbISS4mMFprEcqMZYk0yeOVvfqKIJP6LQ", "quantity": "1", "product_id": "5"}',
                'applied_cart_rule_ids' => '',
                'base_discount_amount' => '0.0000',
                'base_price' => '6.0000',
                'base_tax_amount' => '0.0000',
                'base_total' => '6.0000',
                'base_total_weight' => '40.0000',
                'cart_id' => 7,
                'coupon_code' => NULL,
                'created_at' => '2021-03-25 15:44:08',
                'custom_price' => NULL,
                'discount_amount' => '0.0000',
                'discount_percent' => '0.0000',
                'id' => 8,
                'name' => 'inner wear',
                'parent_id' => NULL,
                'price' => '6.0000',
                'product_id' => 5,
                'quantity' => 1,
                'sku' => '89',
                'tax_amount' => '0.0000',
                'tax_category_id' => NULL,
                'tax_percent' => '0.0000',
                'total' => '6.0000',
                'total_weight' => '40.0000',
                'type' => 'simple',
                'updated_at' => '2021-04-03 15:13:59',
                'weight' => '40.0000',
            ),
            8 => 
            array (
                'additional' => '{"quantity": 1}',
                'applied_cart_rule_ids' => '',
                'base_discount_amount' => '0.0000',
                'base_price' => '10.0000',
                'base_tax_amount' => '0.0000',
                'base_total' => '10.0000',
                'base_total_weight' => '20.0000',
                'cart_id' => 8,
                'coupon_code' => NULL,
                'created_at' => '2021-04-07 17:17:58',
                'custom_price' => NULL,
                'discount_amount' => '0.0000',
                'discount_percent' => '0.0000',
                'id' => 9,
                'name' => 'product1',
                'parent_id' => NULL,
                'price' => '10.0000',
                'product_id' => 1,
                'quantity' => 1,
                'sku' => '1',
                'tax_amount' => '0.0000',
                'tax_category_id' => NULL,
                'tax_percent' => '0.0000',
                'total' => '10.0000',
                'total_weight' => '20.0000',
                'type' => 'simple',
                'updated_at' => '2021-04-07 17:17:58',
                'weight' => '20.0000',
            ),
            9 => 
            array (
                'additional' => '{"quantity": 1}',
                'applied_cart_rule_ids' => '',
                'base_discount_amount' => '0.0000',
                'base_price' => '10.0000',
                'base_tax_amount' => '0.0000',
                'base_total' => '10.0000',
                'base_total_weight' => '20.0000',
                'cart_id' => 9,
                'coupon_code' => NULL,
                'created_at' => '2021-04-07 17:28:26',
                'custom_price' => NULL,
                'discount_amount' => '0.0000',
                'discount_percent' => '0.0000',
                'id' => 10,
                'name' => 'product1',
                'parent_id' => NULL,
                'price' => '10.0000',
                'product_id' => 1,
                'quantity' => 1,
                'sku' => '1',
                'tax_amount' => '0.0000',
                'tax_category_id' => NULL,
                'tax_percent' => '0.0000',
                'total' => '10.0000',
                'total_weight' => '20.0000',
                'type' => 'simple',
                'updated_at' => '2021-04-07 17:28:26',
                'weight' => '20.0000',
            ),
            10 => 
            array (
                'additional' => '{"quantity": 1}',
                'applied_cart_rule_ids' => '',
                'base_discount_amount' => '0.0000',
                'base_price' => '10.0000',
                'base_tax_amount' => '0.0000',
                'base_total' => '10.0000',
                'base_total_weight' => '20.0000',
                'cart_id' => 10,
                'coupon_code' => NULL,
                'created_at' => '2021-04-07 17:31:46',
                'custom_price' => NULL,
                'discount_amount' => '0.0000',
                'discount_percent' => '0.0000',
                'id' => 11,
                'name' => 'product1',
                'parent_id' => NULL,
                'price' => '10.0000',
                'product_id' => 1,
                'quantity' => 1,
                'sku' => '1',
                'tax_amount' => '0.0000',
                'tax_category_id' => NULL,
                'tax_percent' => '0.0000',
                'total' => '10.0000',
                'total_weight' => '20.0000',
                'type' => 'simple',
                'updated_at' => '2021-04-07 17:31:46',
                'weight' => '20.0000',
            ),
        ));
        
        
    }
}