<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customers')->delete();
        
        \DB::table('customers')->insert(array (
            0 => 
            array (
                'api_token' => 'DnZflaERPoFnxI6ci4S4zddKR32oeM8IuiOfFBIpOJR3YwnRbQsttauLA4tLRz7WdOhWRamJxdyDV7DP',
                'created_at' => '2021-03-22 14:33:36',
                'customer_group_id' => 2,
                'date_of_birth' => NULL,
                'email' => 'prashantsingh2408@gmail.com',
                'first_name' => 'prashantupdated',
                'gender' => 'm',
                'id' => 1,
                'is_verified' => 1,
                'last_name' => 'singhupdated',
                'notes' => NULL,
                'password' => '$2y$10$j08KOJyqnJeIiLKhN0CpJe89foQx8sZTAMxoPsFRRvaTtnfdR/oru',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => '5cd144a22f8803a411c6912b2b3af29c',
                'updated_at' => '2021-04-03 16:46:51',
            ),
            1 => 
            array (
                'api_token' => 'mfhqIa7TEuAsM6RqYJcafkqzdRoOU8c0I3BGbiiX6RNJ9doF32Shn7QSdu1h9avGNkL42zgmmQveJ8VF',
                'created_at' => '2021-03-23 11:14:36',
                'customer_group_id' => 2,
                'date_of_birth' => NULL,
                'email' => 'imz@gmail.com',
                'first_name' => 'Md Imtiyaz ',
                'gender' => NULL,
                'id' => 2,
                'is_verified' => 1,
                'last_name' => 'Alam',
                'notes' => NULL,
                'password' => '$2y$10$7YoXgdUklxXC4pys3hpFy.pXKvaDUL78c34osG0vwtix96MtuziEy',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => 'bfccbb9c9e0ec0c92aead8afec3922b0',
                'updated_at' => '2021-03-23 11:14:36',
            ),
            2 => 
            array (
                'api_token' => 'KHAg95GJNyyN81DooIBznrO9WyXBWW4sM7BoZpGQUrEWJhrVLbymHt9zDAiHhrA4OzRRSUUwLWH0c42N',
                'created_at' => '2021-03-31 15:01:26',
                'customer_group_id' => 2,
                'date_of_birth' => NULL,
                'email' => 'lokesh@pegalogics.comm',
                'first_name' => 'Lokesh',
                'gender' => NULL,
                'id' => 3,
                'is_verified' => 1,
                'last_name' => 'Dewangan',
                'notes' => NULL,
                'password' => '$2y$10$VVsfB8cPHdw4mh0yOjJJCuCZsFnYYRyWx6KfX2WpAe1CXEj6ogpnG',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => 'cd6e6e0fc14215a298d73912621717d1',
                'updated_at' => '2021-03-31 15:01:26',
            ),
            3 => 
            array (
                'api_token' => 'p7VBkTymoNPBvCdkyOy7jiMl8UxfO4RwM75qu4C3V7v0KS1XOlhKLPV6tl39THdKNeLPFIUBdkNrdPCQ',
                'created_at' => '2021-03-31 16:16:34',
                'customer_group_id' => 2,
                'date_of_birth' => NULL,
                'email' => 'lokeshdewangan500@gmail.com',
                'first_name' => 'Lokesh',
                'gender' => NULL,
                'id' => 4,
                'is_verified' => 1,
                'last_name' => 'Dewangan',
                'notes' => NULL,
                'password' => '$2y$10$H69RQcTPR6j7xkJKczh8jODaC8sN00Cn8Dljopsi0ppjN0i333uLy',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => '412c388c9627c27c20830cc9da6544f4',
                'updated_at' => '2021-03-31 16:16:34',
            ),
            4 => 
            array (
                'api_token' => NULL,
                'created_at' => '2021-04-01 10:52:17',
                'customer_group_id' => 2,
                'date_of_birth' => NULL,
                'email' => 'john@example.com',
                'first_name' => 'prasahnt',
                'gender' => NULL,
                'id' => 5,
                'is_verified' => 1,
                'last_name' => 'fdddsdsd',
                'notes' => NULL,
                'password' => '$2y$10$6AwrP3AvINODZDfcMY65LOsvXkxZ550UqKWydWHCRwlstC6nG9/0u',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => NULL,
                'updated_at' => '2021-04-01 10:52:17',
            ),
            5 => 
            array (
                'api_token' => NULL,
                'created_at' => '2021-04-01 10:53:44',
                'customer_group_id' => 2,
                'date_of_birth' => NULL,
                'email' => 'john@exam1ple.com',
                'first_name' => 'prasahnt',
                'gender' => NULL,
                'id' => 6,
                'is_verified' => 1,
                'last_name' => 'fdddsdsd',
                'notes' => NULL,
                'password' => '$2y$10$MUVNLZtkn6FBIaYK53RMeOujnE7ZAPD8Jk/9xPFJddoqCgds3JCV2',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => NULL,
                'updated_at' => '2021-04-01 10:53:44',
            ),
            6 => 
            array (
                'api_token' => NULL,
                'created_at' => '2021-04-01 11:25:18',
                'customer_group_id' => 2,
                'date_of_birth' => NULL,
                'email' => 'john@exa8m1ple.com',
                'first_name' => 'prasahntKK',
                'gender' => NULL,
                'id' => 7,
                'is_verified' => 1,
                'last_name' => 'fdddsdsdKK',
                'notes' => NULL,
                'password' => '$2y$10$5sil00BhSOowg4wiBwAoMu0c46.6aqKs2pf0CB92t5Rl3CqKrxok.',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => NULL,
                'updated_at' => '2021-04-01 11:25:18',
            ),
            7 => 
            array (
                'api_token' => NULL,
                'created_at' => '2021-04-02 14:24:24',
                'customer_group_id' => NULL,
                'date_of_birth' => NULL,
                'email' => 'lokesh@pegalogics.com',
                'first_name' => 'Lokesh',
                'gender' => NULL,
                'id' => 14,
                'is_verified' => 0,
                'last_name' => 'Kumar',
                'notes' => NULL,
                'password' => '$2y$10$17ojMtw.txZBkNSlhemKv.pqy7S8hTK0xe8uGKyEP5Hgcn9O3A3bC',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => NULL,
                'updated_at' => '2021-04-02 14:24:24',
            ),
            8 => 
            array (
                'api_token' => NULL,
                'created_at' => '2021-04-02 14:26:28',
                'customer_group_id' => NULL,
                'date_of_birth' => NULL,
                'email' => 'lokesh2@pegalogics.com',
                'first_name' => 'Lokesh',
                'gender' => NULL,
                'id' => 16,
                'is_verified' => 0,
                'last_name' => 'Kumar',
                'notes' => NULL,
                'password' => '$2y$10$YLTOMq8jZAKFETuyDB5/UuFvPqEOoWO5GUyHrbjRNe66hM.zc8B.i',
                'phone' => '7678120129',
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => NULL,
                'updated_at' => '2021-04-02 14:26:28',
            ),
            9 => 
            array (
                'api_token' => NULL,
                'created_at' => '2021-04-02 14:28:58',
                'customer_group_id' => NULL,
                'date_of_birth' => NULL,
                'email' => 'harishankar@gmail.com',
                'first_name' => 'hari',
                'gender' => NULL,
                'id' => 17,
                'is_verified' => 0,
                'last_name' => 'Dash',
                'notes' => NULL,
                'password' => '$2y$10$iGVN3pju3L9Y5Gvo/YGgAO7jKHf6EqaHB7tttcUPocUWsy290rJnu',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => NULL,
                'updated_at' => '2021-04-02 14:28:58',
            ),
            10 => 
            array (
                'api_token' => NULL,
                'created_at' => '2021-04-05 16:58:13',
                'customer_group_id' => NULL,
                'date_of_birth' => NULL,
                'email' => 'prashantsingh00@gmail.com',
                'first_name' => 'prashant22',
                'gender' => 'null',
                'id' => 18,
                'is_verified' => 0,
                'last_name' => 'singh22',
                'notes' => NULL,
                'password' => '$2y$10$q4FJgHKMzxXtdXjKYkrFN.fZNiSTAvX72dLw85CJCNPKooRIHGrEe',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => 'Authorization',
                'updated_at' => '2021-04-05 17:45:27',
            ),
            11 => 
            array (
                'api_token' => NULL,
                'created_at' => '2021-04-06 10:29:40',
                'customer_group_id' => NULL,
                'date_of_birth' => NULL,
                'email' => 'prashantsingh000@gmail.com',
                'first_name' => 'prasahant99',
                'gender' => 'null',
                'id' => 20,
                'is_verified' => 0,
                'last_name' => 'singh99',
                'notes' => NULL,
                'password' => '$2y$10$SEhIaIh0xvja6eNx5lSuLO4.8sZtEgEQf3mUCuzVH1hhnKeq9Cp7W',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => 'Authorization',
                'updated_at' => '2021-04-06 11:12:02',
            ),
            12 => 
            array (
                'api_token' => NULL,
                'created_at' => '2021-04-06 13:10:16',
                'customer_group_id' => NULL,
                'date_of_birth' => NULL,
                'email' => 'prashantsingh2408cloud@gmail.com',
                'first_name' => 'prasahant999',
                'gender' => NULL,
                'id' => 22,
                'is_verified' => 0,
                'last_name' => 'singh999',
                'notes' => NULL,
                'password' => '$2y$10$ak/8z2CNLHiOPmFyuRi0mOiMO8.EyHmB/uSUD08l2Ij2NT8LTHLJ2',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => 'Authorization',
                'updated_at' => '2021-04-07 16:56:41',
            ),
            13 => 
            array (
                'api_token' => NULL,
                'created_at' => '2021-04-07 10:31:56',
                'customer_group_id' => NULL,
                'date_of_birth' => NULL,
                'email' => 'prashantsingh999@gmail.com',
                'first_name' => 'prashant999',
                'gender' => NULL,
                'id' => 24,
                'is_verified' => 0,
                'last_name' => 'singh999',
                'notes' => NULL,
                'password' => '$2y$10$9cpClGG350z/5Re00.l8JO5jca.rBpFWvhVYeDF8tNjxS.SiyzeJK',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => 'Authorization',
                'updated_at' => '2021-04-07 10:31:56',
            ),
            14 => 
            array (
                'api_token' => NULL,
                'created_at' => '2021-04-07 10:40:45',
                'customer_group_id' => NULL,
                'date_of_birth' => NULL,
                'email' => 'prashantsingh2411cloud@gmail.com',
                'first_name' => 'prasahant99',
                'gender' => NULL,
                'id' => 25,
                'is_verified' => 0,
                'last_name' => 'singh99',
                'notes' => NULL,
                'password' => '$2y$10$XNg2t2.sobfjgEFY1se3feJpLao.UD0IqZpyJCNh0.WQqB5z6NL6K',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => 'Authorization',
                'updated_at' => '2021-04-07 10:40:45',
            ),
            15 => 
            array (
                'api_token' => NULL,
                'created_at' => '2021-04-07 12:53:30',
                'customer_group_id' => NULL,
                'date_of_birth' => NULL,
                'email' => 'prashantsingh12345@gmail.com',
                'first_name' => 'prasahant999',
                'gender' => 'null',
                'id' => 27,
                'is_verified' => 0,
                'last_name' => 'singh999',
                'notes' => NULL,
                'password' => '$2y$10$kXQztDeZ9Yw2.vgXyFBDP.G8ksjInpmsQPLnnyqmcUuVVKMze1iyC',
                'phone' => NULL,
                'remember_token' => NULL,
                'status' => 1,
                'subscribed_to_news_letter' => 0,
                'token' => 'Authorization',
                'updated_at' => '2021-04-07 13:55:38',
            ),
        ));
        
        
    }
}