<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Webkul\Velocity\Database\Seeders\VelocityMetaDataSeeder;
use Webkul\Admin\Database\Seeders\DatabaseSeeder as BagistoDatabaseSeeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $this->call(BagistoDatabaseSeeder::class);
        $this->call(VelocityMetaDataSeeder::class);
        $this->call(AddressesTableSeeder::class);
        $this->call(AdminPasswordResetsTableSeeder::class);
        $this->call(AdminsTableSeeder::class);
        $this->call(AttributeFamiliesTableSeeder::class);
        $this->call(AttributeGroupMappingsTableSeeder::class);
        $this->call(AttributeGroupsTableSeeder::class);
        $this->call(AttributeOptionTranslationsTableSeeder::class);
        $this->call(AttributeOptionsTableSeeder::class);
        $this->call(AttributeTranslationsTableSeeder::class);
        $this->call(AttributesTableSeeder::class);
        $this->call(BookingProductAppointmentSlotsTableSeeder::class);
        $this->call(BookingProductDefaultSlotsTableSeeder::class);
        $this->call(BookingProductEventTicketTranslationsTableSeeder::class);
        $this->call(BookingProductEventTicketsTableSeeder::class);
        $this->call(BookingProductRentalSlotsTableSeeder::class);
        $this->call(BookingProductTableSlotsTableSeeder::class);
        $this->call(BookingProductsTableSeeder::class);
        $this->call(BookingsTableSeeder::class);
        $this->call(CartTableSeeder::class);
        $this->call(CartItemInventoriesTableSeeder::class);
        $this->call(CartItemsTableSeeder::class);
        $this->call(CartPaymentTableSeeder::class);
        $this->call(CartRuleChannelsTableSeeder::class);
        $this->call(CartRuleCouponUsageTableSeeder::class);
        $this->call(CartRuleCouponsTableSeeder::class);
        $this->call(CartRuleCustomerGroupsTableSeeder::class);
        $this->call(CartRuleCustomersTableSeeder::class);
        $this->call(CartRuleTranslationsTableSeeder::class);
        $this->call(CartRulesTableSeeder::class);
        $this->call(CartShippingRatesTableSeeder::class);
        $this->call(CatalogRuleChannelsTableSeeder::class);
        $this->call(CatalogRuleCustomerGroupsTableSeeder::class);
        $this->call(CatalogRuleProductPricesTableSeeder::class);
        $this->call(CatalogRuleProductsTableSeeder::class);
        $this->call(CatalogRulesTableSeeder::class);
        $this->call(CategoriesTableSeeder::class);
        $this->call(CategoryFilterableAttributesTableSeeder::class);
        $this->call(CategoryTranslationsTableSeeder::class);
        $this->call(ChannelCurrenciesTableSeeder::class);
        $this->call(ChannelInventorySourcesTableSeeder::class);
        $this->call(ChannelLocalesTableSeeder::class);
        $this->call(ChannelTranslationsTableSeeder::class);
        $this->call(ChannelsTableSeeder::class);
        $this->call(CmsPageChannelsTableSeeder::class);
        $this->call(CmsPageTranslationsTableSeeder::class);
        $this->call(CmsPagesTableSeeder::class);
        $this->call(CoreConfigTableSeeder::class);
        $this->call(CountriesTableSeeder::class);
        $this->call(CountryStateTranslationsTableSeeder::class);
        $this->call(CountryStatesTableSeeder::class);
        $this->call(CountryTranslationsTableSeeder::class);
        $this->call(CurrenciesTableSeeder::class);
        $this->call(CurrencyExchangeRatesTableSeeder::class);
        $this->call(CustomerGroupsTableSeeder::class);
        $this->call(CustomerPasswordResetsTableSeeder::class);
        $this->call(CustomerSocialAccountsTableSeeder::class);
        $this->call(CustomersTableSeeder::class);
        $this->call(DownloadableLinkPurchasedTableSeeder::class);
        $this->call(InventorySourcesTableSeeder::class);
        $this->call(InvoiceItemsTableSeeder::class);
        $this->call(InvoicesTableSeeder::class);
        $this->call(JobsTableSeeder::class);
        $this->call(LocalesTableSeeder::class);
        $this->call(MarketingCampaignsTableSeeder::class);
        $this->call(MarketingEventsTableSeeder::class);
        $this->call(MarketingTemplatesTableSeeder::class);
        $this->call(OrderBrandsTableSeeder::class);
        $this->call(OrderCommentsTableSeeder::class);
        $this->call(OrderItemsTableSeeder::class);
        $this->call(OrderPaymentTableSeeder::class);
        $this->call(OrderTransactionsTableSeeder::class);
        $this->call(OrdersTableSeeder::class);
        $this->call(PasswordResetsTableSeeder::class);
        $this->call(ProductAttributeValuesTableSeeder::class);
        $this->call(ProductBundleOptionProductsTableSeeder::class);
        $this->call(ProductBundleOptionTranslationsTableSeeder::class);
        $this->call(ProductBundleOptionsTableSeeder::class);
        $this->call(ProductCategoriesTableSeeder::class);
        $this->call(ProductCrossSellsTableSeeder::class);
        $this->call(ProductCustomerGroupPricesTableSeeder::class);
        $this->call(ProductDownloadableLinkTranslationsTableSeeder::class);
        $this->call(ProductDownloadableLinksTableSeeder::class);
        $this->call(ProductDownloadableSampleTranslationsTableSeeder::class);
        $this->call(ProductDownloadableSamplesTableSeeder::class);
        $this->call(ProductFlatTableSeeder::class);
        $this->call(ProductGroupedProductsTableSeeder::class);
        $this->call(ProductImagesTableSeeder::class);
        $this->call(ProductInventoriesTableSeeder::class);
        $this->call(ProductOrderedInventoriesTableSeeder::class);
        $this->call(ProductRelationsTableSeeder::class);
        $this->call(ProductReviewsTableSeeder::class);
        $this->call(ProductSuperAttributesTableSeeder::class);
        $this->call(ProductUpSellsTableSeeder::class);
        $this->call(ProductVideosTableSeeder::class);
        $this->call(ProductsTableSeeder::class);
        $this->call(RefundItemsTableSeeder::class);
        $this->call(RefundsTableSeeder::class);
        $this->call(RolesTableSeeder::class);
        $this->call(ShipmentItemsTableSeeder::class);
        $this->call(ShipmentsTableSeeder::class);
        $this->call(SlidersTableSeeder::class);
        $this->call(SubscribersListTableSeeder::class);
        $this->call(TaxCategoriesTableSeeder::class);
        $this->call(TaxCategoriesTaxRatesTableSeeder::class);
        $this->call(TaxRatesTableSeeder::class);
        $this->call(UsersTableSeeder::class);
        $this->call(VelocityContentsTableSeeder::class);
        $this->call(VelocityContentsTranslationsTableSeeder::class);
        $this->call(VelocityCustomerCompareProductsTableSeeder::class);
        $this->call(VelocityMetaDataTableSeeder::class);
        $this->call(WishlistTableSeeder::class);
    }
}
