<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductAttributeValuesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_attribute_values')->delete();
        
        \DB::table('product_attribute_values')->insert(array (
            0 => 
            array (
                'attribute_id' => 9,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 1,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 1,
                'text_value' => '<p>product 1 descrition</p>',
            ),
            1 => 
            array (
                'attribute_id' => 10,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 2,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 1,
                'text_value' => '<p>product 1 descrition</p>',
            ),
            2 => 
            array (
                'attribute_id' => 1,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 3,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => '1',
            ),
            3 => 
            array (
                'attribute_id' => 2,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 4,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 1,
                'text_value' => 'product1',
            ),
            4 => 
            array (
                'attribute_id' => 3,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 5,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => 'product1',
            ),
            5 => 
            array (
                'attribute_id' => 4,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 6,
                'integer_value' => 0,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => NULL,
            ),
            6 => 
            array (
                'attribute_id' => 5,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 7,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => NULL,
            ),
            7 => 
            array (
                'attribute_id' => 6,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 8,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => NULL,
            ),
            8 => 
            array (
                'attribute_id' => 7,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 9,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => NULL,
            ),
            9 => 
            array (
                'attribute_id' => 8,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 10,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => NULL,
            ),
            10 => 
            array (
                'attribute_id' => 23,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 11,
                'integer_value' => 1,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => NULL,
            ),
            11 => 
            array (
                'attribute_id' => 24,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 12,
                'integer_value' => 6,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => NULL,
            ),
            12 => 
            array (
                'attribute_id' => 26,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 13,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => NULL,
            ),
            13 => 
            array (
                'attribute_id' => 27,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 14,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => '1',
            ),
            14 => 
            array (
                'attribute_id' => 16,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 15,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 1,
                'text_value' => 'Meta Title sectioin',
            ),
            15 => 
            array (
                'attribute_id' => 17,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 16,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 1,
                'text_value' => 'meta keywords section',
            ),
            16 => 
            array (
                'attribute_id' => 18,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 17,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 1,
                'text_value' => 'Meta description section',
            ),
            17 => 
            array (
                'attribute_id' => 11,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => '10.0000',
                'id' => 18,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => NULL,
            ),
            18 => 
            array (
                'attribute_id' => 12,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => '20.0000',
                'id' => 19,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => NULL,
            ),
            19 => 
            array (
                'attribute_id' => 13,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => '5.0000',
                'id' => 20,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => NULL,
            ),
            20 => 
            array (
                'attribute_id' => 14,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => '2021-03-11',
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 21,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => NULL,
            ),
            21 => 
            array (
                'attribute_id' => 15,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => '2021-03-20',
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 22,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => NULL,
            ),
            22 => 
            array (
                'attribute_id' => 19,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 23,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => '',
            ),
            23 => 
            array (
                'attribute_id' => 20,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 24,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => '',
            ),
            24 => 
            array (
                'attribute_id' => 21,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 25,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => '',
            ),
            25 => 
            array (
                'attribute_id' => 22,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 26,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 1,
                'text_value' => '20',
            ),
            26 => 
            array (
                'attribute_id' => 9,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 27,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 3,
                'text_value' => '<p>product 1 description</p>',
            ),
            27 => 
            array (
                'attribute_id' => 10,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 28,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 3,
                'text_value' => '<p>product 1 description</p>',
            ),
            28 => 
            array (
                'attribute_id' => 1,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 29,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => '3',
            ),
            29 => 
            array (
                'attribute_id' => 2,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 30,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 3,
                'text_value' => 'product 3',
            ),
            30 => 
            array (
                'attribute_id' => 3,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 31,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => 'product-3',
            ),
            31 => 
            array (
                'attribute_id' => 4,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 32,
                'integer_value' => 0,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => NULL,
            ),
            32 => 
            array (
                'attribute_id' => 5,
                'boolean_value' => 0,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 33,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => NULL,
            ),
            33 => 
            array (
                'attribute_id' => 6,
                'boolean_value' => 0,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 34,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => NULL,
            ),
            34 => 
            array (
                'attribute_id' => 7,
                'boolean_value' => 0,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 35,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => NULL,
            ),
            35 => 
            array (
                'attribute_id' => 8,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 36,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => NULL,
            ),
            36 => 
            array (
                'attribute_id' => 23,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 37,
                'integer_value' => 1,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => NULL,
            ),
            37 => 
            array (
                'attribute_id' => 24,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 38,
                'integer_value' => 6,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => NULL,
            ),
            38 => 
            array (
                'attribute_id' => 26,
                'boolean_value' => 0,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 39,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => NULL,
            ),
            39 => 
            array (
                'attribute_id' => 27,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 40,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => 'product 3',
            ),
            40 => 
            array (
                'attribute_id' => 16,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 41,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 3,
                'text_value' => '',
            ),
            41 => 
            array (
                'attribute_id' => 17,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 42,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 3,
                'text_value' => '',
            ),
            42 => 
            array (
                'attribute_id' => 18,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 43,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 3,
                'text_value' => '',
            ),
            43 => 
            array (
                'attribute_id' => 11,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => '50.0000',
                'id' => 44,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => NULL,
            ),
            44 => 
            array (
                'attribute_id' => 12,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 45,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => NULL,
            ),
            45 => 
            array (
                'attribute_id' => 13,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => '7.0000',
                'id' => 46,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => NULL,
            ),
            46 => 
            array (
                'attribute_id' => 14,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 47,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => NULL,
            ),
            47 => 
            array (
                'attribute_id' => 15,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 48,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => NULL,
            ),
            48 => 
            array (
                'attribute_id' => 19,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 49,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => '',
            ),
            49 => 
            array (
                'attribute_id' => 20,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 50,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => '',
            ),
            50 => 
            array (
                'attribute_id' => 21,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 51,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => '',
            ),
            51 => 
            array (
                'attribute_id' => 22,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 52,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 3,
                'text_value' => '20',
            ),
            52 => 
            array (
                'attribute_id' => 9,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 53,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 4,
                'text_value' => '<p>des</p>',
            ),
            53 => 
            array (
                'attribute_id' => 10,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 54,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 4,
                'text_value' => '<p>des</p>',
            ),
            54 => 
            array (
                'attribute_id' => 1,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 55,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => '88',
            ),
            55 => 
            array (
                'attribute_id' => 2,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 56,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 4,
                'text_value' => 'tiptop',
            ),
            56 => 
            array (
                'attribute_id' => 3,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 57,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => 'tiptop',
            ),
            57 => 
            array (
                'attribute_id' => 4,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 58,
                'integer_value' => 0,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => NULL,
            ),
            58 => 
            array (
                'attribute_id' => 5,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 59,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => NULL,
            ),
            59 => 
            array (
                'attribute_id' => 6,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 60,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => NULL,
            ),
            60 => 
            array (
                'attribute_id' => 7,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 61,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => NULL,
            ),
            61 => 
            array (
                'attribute_id' => 8,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 62,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => NULL,
            ),
            62 => 
            array (
                'attribute_id' => 23,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 63,
                'integer_value' => 1,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => NULL,
            ),
            63 => 
            array (
                'attribute_id' => 24,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 64,
                'integer_value' => 6,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => NULL,
            ),
            64 => 
            array (
                'attribute_id' => 26,
                'boolean_value' => 0,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 65,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => NULL,
            ),
            65 => 
            array (
                'attribute_id' => 27,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 66,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => 'tiptop',
            ),
            66 => 
            array (
                'attribute_id' => 16,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 67,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 4,
                'text_value' => '',
            ),
            67 => 
            array (
                'attribute_id' => 17,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 68,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 4,
                'text_value' => '',
            ),
            68 => 
            array (
                'attribute_id' => 18,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 69,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 4,
                'text_value' => '',
            ),
            69 => 
            array (
                'attribute_id' => 11,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => '40.0000',
                'id' => 70,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => NULL,
            ),
            70 => 
            array (
                'attribute_id' => 12,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => '40.0000',
                'id' => 71,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => NULL,
            ),
            71 => 
            array (
                'attribute_id' => 13,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => '39.0000',
                'id' => 72,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => NULL,
            ),
            72 => 
            array (
                'attribute_id' => 14,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 73,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => NULL,
            ),
            73 => 
            array (
                'attribute_id' => 15,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 74,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => NULL,
            ),
            74 => 
            array (
                'attribute_id' => 19,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 75,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => '',
            ),
            75 => 
            array (
                'attribute_id' => 20,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 76,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => '',
            ),
            76 => 
            array (
                'attribute_id' => 21,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 77,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => '',
            ),
            77 => 
            array (
                'attribute_id' => 22,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 78,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 4,
                'text_value' => '8',
            ),
            78 => 
            array (
                'attribute_id' => 9,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 79,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 5,
                'text_value' => '<p>brand</p>',
            ),
            79 => 
            array (
                'attribute_id' => 10,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 80,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 5,
                'text_value' => '<p>jockey</p>',
            ),
            80 => 
            array (
                'attribute_id' => 1,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 81,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => '89',
            ),
            81 => 
            array (
                'attribute_id' => 2,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 82,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 5,
                'text_value' => 'inner wear',
            ),
            82 => 
            array (
                'attribute_id' => 3,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 83,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => 'inner-wear',
            ),
            83 => 
            array (
                'attribute_id' => 4,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 84,
                'integer_value' => 0,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => NULL,
            ),
            84 => 
            array (
                'attribute_id' => 5,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 85,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => NULL,
            ),
            85 => 
            array (
                'attribute_id' => 6,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 86,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => NULL,
            ),
            86 => 
            array (
                'attribute_id' => 7,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 87,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => NULL,
            ),
            87 => 
            array (
                'attribute_id' => 8,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 88,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => NULL,
            ),
            88 => 
            array (
                'attribute_id' => 23,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 89,
                'integer_value' => 1,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => NULL,
            ),
            89 => 
            array (
                'attribute_id' => 24,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 90,
                'integer_value' => 8,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => NULL,
            ),
            90 => 
            array (
                'attribute_id' => 26,
                'boolean_value' => 1,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 91,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => NULL,
            ),
            91 => 
            array (
                'attribute_id' => 27,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 92,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => 'jockey ',
            ),
            92 => 
            array (
                'attribute_id' => 16,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 93,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 5,
                'text_value' => '',
            ),
            93 => 
            array (
                'attribute_id' => 17,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 94,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 5,
                'text_value' => '',
            ),
            94 => 
            array (
                'attribute_id' => 18,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 95,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => 'en',
                'product_id' => 5,
                'text_value' => '',
            ),
            95 => 
            array (
                'attribute_id' => 11,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => '180.0000',
                'id' => 96,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => NULL,
            ),
            96 => 
            array (
                'attribute_id' => 12,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => '180.0000',
                'id' => 97,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => NULL,
            ),
            97 => 
            array (
                'attribute_id' => 13,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => '6.0000',
                'id' => 98,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => NULL,
            ),
            98 => 
            array (
                'attribute_id' => 14,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 99,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => NULL,
            ),
            99 => 
            array (
                'attribute_id' => 15,
                'boolean_value' => NULL,
                'channel' => 'default',
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 100,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => NULL,
            ),
            100 => 
            array (
                'attribute_id' => 19,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 101,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => '',
            ),
            101 => 
            array (
                'attribute_id' => 20,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 102,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => '',
            ),
            102 => 
            array (
                'attribute_id' => 21,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 103,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => '',
            ),
            103 => 
            array (
                'attribute_id' => 22,
                'boolean_value' => NULL,
                'channel' => NULL,
                'date_value' => NULL,
                'datetime_value' => NULL,
                'float_value' => NULL,
                'id' => 104,
                'integer_value' => NULL,
                'json_value' => NULL,
                'locale' => NULL,
                'product_id' => 5,
                'text_value' => '40',
            ),
        ));
        
        
    }
}