<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductFlatTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_flat')->delete();
        
        \DB::table('product_flat')->insert(array (
            0 => 
            array (
                'channel' => 'default',
                'color' => 1,
                'color_label' => 'Red',
                'cost' => '20.0000',
                'created_at' => '2021-03-22 10:58:07',
                'depth' => '0.0000',
                'description' => '<p>product 1 descrition</p>',
                'featured' => 1,
                'height' => '0.0000',
                'id' => 1,
                'locale' => 'en',
                'max_price' => '10.0000',
                'meta_description' => 'Meta description section',
                'meta_keywords' => 'meta keywords section',
                'meta_title' => 'Meta Title sectioin',
                'min_price' => '10.0000',
                'name' => 'product1',
                'new' => 1,
                'parent_id' => NULL,
                'price' => '10.0000',
                'product_id' => 1,
                'product_number' => '1',
                'short_description' => '<p>product 1 descrition</p>',
                'size' => 6,
                'size_label' => 'S',
                'sku' => '1',
                'special_price' => '5.0000',
                'special_price_from' => '2021-03-11',
                'special_price_to' => '2021-03-20',
                'status' => 1,
                'thumbnail' => NULL,
                'updated_at' => '2021-03-22 10:58:07',
                'url_key' => 'product1',
                'visible_individually' => 1,
                'weight' => '20.0000',
                'width' => '0.0000',
            ),
            1 => 
            array (
                'channel' => 'default',
                'color' => NULL,
                'color_label' => NULL,
                'cost' => NULL,
                'created_at' => '2021-03-22 16:06:46',
                'depth' => NULL,
                'description' => NULL,
                'featured' => NULL,
                'height' => NULL,
                'id' => 2,
                'locale' => 'en',
                'max_price' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'meta_title' => NULL,
                'min_price' => NULL,
                'name' => NULL,
                'new' => NULL,
                'parent_id' => NULL,
                'price' => NULL,
                'product_id' => 2,
                'product_number' => NULL,
                'short_description' => NULL,
                'size' => NULL,
                'size_label' => NULL,
                'sku' => '',
                'special_price' => NULL,
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'status' => NULL,
                'thumbnail' => NULL,
                'updated_at' => '2021-03-22 16:06:46',
                'url_key' => NULL,
                'visible_individually' => NULL,
                'weight' => NULL,
                'width' => NULL,
            ),
            2 => 
            array (
                'channel' => 'default',
                'color' => 1,
                'color_label' => 'Red',
                'cost' => NULL,
                'created_at' => '2021-03-23 17:25:01',
                'depth' => '0.0000',
                'description' => '<p>product 1 description</p>',
                'featured' => 0,
                'height' => '0.0000',
                'id' => 3,
                'locale' => 'en',
                'max_price' => '50.0000',
                'meta_description' => '',
                'meta_keywords' => '',
                'meta_title' => '',
                'min_price' => '7.0000',
                'name' => 'product 3',
                'new' => 0,
                'parent_id' => NULL,
                'price' => '50.0000',
                'product_id' => 3,
                'product_number' => 'product 3',
                'short_description' => '<p>product 1 description</p>',
                'size' => 6,
                'size_label' => 'S',
                'sku' => '3',
                'special_price' => '7.0000',
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'status' => 1,
                'thumbnail' => NULL,
                'updated_at' => '2021-03-23 17:25:01',
                'url_key' => 'product-3',
                'visible_individually' => 0,
                'weight' => '20.0000',
                'width' => '0.0000',
            ),
            3 => 
            array (
                'channel' => 'default',
                'color' => 1,
                'color_label' => 'Red',
                'cost' => '40.0000',
                'created_at' => '2021-03-25 15:07:05',
                'depth' => '0.0000',
                'description' => '<p>des</p>',
                'featured' => 1,
                'height' => '0.0000',
                'id' => 4,
                'locale' => 'en',
                'max_price' => '40.0000',
                'meta_description' => '',
                'meta_keywords' => '',
                'meta_title' => '',
                'min_price' => '39.0000',
                'name' => 'tiptop',
                'new' => 1,
                'parent_id' => NULL,
                'price' => '40.0000',
                'product_id' => 4,
                'product_number' => 'tiptop',
                'short_description' => '<p>des</p>',
                'size' => 6,
                'size_label' => 'S',
                'sku' => '88',
                'special_price' => '39.0000',
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'status' => 1,
                'thumbnail' => NULL,
                'updated_at' => '2021-03-25 15:07:05',
                'url_key' => 'tiptop',
                'visible_individually' => 1,
                'weight' => '8.0000',
                'width' => '0.0000',
            ),
            4 => 
            array (
                'channel' => 'default',
                'color' => 1,
                'color_label' => 'Red',
                'cost' => '180.0000',
                'created_at' => '2021-03-25 15:38:19',
                'depth' => '0.0000',
                'description' => '<p>jockey</p>',
                'featured' => 1,
                'height' => '0.0000',
                'id' => 5,
                'locale' => 'en',
                'max_price' => '180.0000',
                'meta_description' => '',
                'meta_keywords' => '',
                'meta_title' => '',
                'min_price' => '6.0000',
                'name' => 'inner wear',
                'new' => 1,
                'parent_id' => NULL,
                'price' => '180.0000',
                'product_id' => 5,
                'product_number' => 'jockey ',
                'short_description' => '<p>brand</p>',
                'size' => 8,
                'size_label' => 'L',
                'sku' => '89',
                'special_price' => '6.0000',
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'status' => 1,
                'thumbnail' => NULL,
                'updated_at' => '2021-03-25 15:38:19',
                'url_key' => 'inner-wear',
                'visible_individually' => 1,
                'weight' => '40.0000',
                'width' => '0.0000',
            ),
            5 => 
            array (
                'channel' => 'default',
                'color' => NULL,
                'color_label' => NULL,
                'cost' => NULL,
                'created_at' => '2021-04-03 12:48:08',
                'depth' => NULL,
                'description' => NULL,
                'featured' => NULL,
                'height' => NULL,
                'id' => 6,
                'locale' => 'en',
                'max_price' => NULL,
                'meta_description' => NULL,
                'meta_keywords' => NULL,
                'meta_title' => NULL,
                'min_price' => NULL,
                'name' => NULL,
                'new' => NULL,
                'parent_id' => NULL,
                'price' => NULL,
                'product_id' => 6,
                'product_number' => NULL,
                'short_description' => NULL,
                'size' => NULL,
                'size_label' => NULL,
                'sku' => '',
                'special_price' => NULL,
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'status' => NULL,
                'thumbnail' => NULL,
                'updated_at' => '2021-04-03 12:48:08',
                'url_key' => NULL,
                'visible_individually' => NULL,
                'weight' => NULL,
                'width' => NULL,
            ),
        ));
        
        
    }
}